### ISSUE TITLE
Carsh

### ISSUE THREAD

**Issue by pz-bottle** [fenggit/FloatWindow#5]

**Comment by pz-bottle** [comment]
下载了demo允许一点show按钮就carsh了

**Comment by pz-bottle** [comment]
carsh日志为：

**Comment by pz-bottle** [comment]
2020-12-09 15:58:38.649 18332-18332/com.fenggit.floatwindow E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fenggit.floatwindow, PID: 18332
    java.lang.RuntimeException: Unable to create service com.fenggit.floatwindow.FloatWindowService: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@591f6c0 -- permission denied for window type 2038
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3450)
        at android.app.ActivityThread.-wrap5(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1726)
        at android.os.Handler.dispatchMessage(Handler.java:113)
        at android.os.Looper.loop(Looper.java:205)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1216)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1077)
     Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@591f6c0 -- permission denied for window type 2038
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:937)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:389)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:114)
        at com.fenggit.floatwindow.FloatWindow.show(FloatWindow.java:211)
        at com.fenggit.floatwindow.FloatWindowService.initView(FloatWindowService.kt:71)
        at com.fenggit.floatwindow.FloatWindowService.onCreate(FloatWindowService.kt:25)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3430)
        at android.app.ActivityThread.-wrap5(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1726) 
        at android.os.Handler.dispatchMessage(Handler.java:113) 
        at android.os.Looper.loop(Looper.java:205) 
        at android.app.ActivityThread.main(ActivityThread.java:6753) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1216) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1077)
